#!/bin/sh -e
# Copyright (c) 2016 The crouton Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# This is a distro-specific bootstrap script, sourced from main.sh, and as such
# has access to all of the variables set by main.sh, namely $tmp (the temporary
# directory), $INSTALLERDIR/$DISTRO, $RELEASE, $BOOTSTRAP_RELEASE (if different
# from $RELEASE), $ARCH, and $MIRROR.

CUR=`pwd`

# Grab the latest release of debootstrap
cd "$tmp"; 
echo 'Downloading latest debootstrap...' 1>&2
d='https://raw.githubusercontent.com/mbgg/debootstrap/master/debootstrap.sh'
if ! wget --no-verbose --timeout=60 -t2 ${d}
then
    echo 'Failed to download debootstrap.
    Check your internet connection or proxy settings and try again.'
    exit 1
fi
chmod 755 debootstrap.sh
cd ..

# Grab the release and drop it into the subdirectory
echo 'Downloading bootstrap files...' 1>&2
PATH="$newpath" DEBOOTSTRAP_DIR="$tmp" $FAKEROOT \
    "$tmp/debootstrap.sh" --foreign --arch="$ARCH" \
    "$RELEASE" "$tmp/$subdir" "$MIRROR" 1>&2

echo 'Remove /dev files as not needed'
rm ${tmp}/${subdir}/dev/*
