#!/bin/sh -e
# Copyright (c) 2016 The crouton Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# This file is sourced from main.sh to update distro-specific defaults.
# It must set at least ARCH and MIRROR if not already specified.

if [ -z "$ARCH" ]; then
    ARCH="`uname -m`"
fi

case "$ARCH" in
x86_64 | amd64) ARCH="x86_64";;
arm*) ARCH="armv7l";;
aarch64) ARCH="aarch64";;
*) error 2 "Invalid architecture '$ARCH'.";;
esac

if [ -z "$MIRROR" ]; then
    MIRROR="${CROUTON_MIRROR_opensuse_arm:-http://download.opensuse.org/ports/}"
fi

